services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  layer1:
    image: tracing-demo
    container_name: layer1
    ports:
      - 8080:8080
    environment:
      PROFILE: layer1
    depends_on:
      - zipkin
  layer2:
    image: tracing-demo
    container_name: layer2
    ports:
      - 8081:8080
    environment:
      PROFILE: layer2
    depends_on:
      - zipkin
  layer3:
    image: tracing-demo
    container_name: layer3
    ports:
      - 8082:8080
    environment:
      PROFILE: layer3
    depends_on:
      - zipkin